backend/testquizapp/testquizapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('main_app.urls', namespace='main_app')),
    path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='api-schema'), name='api-docs')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/testquizapp/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('signin/', views.LoginUserView.as_view(), name='login'),
    path('signup/', views.RegistrationView.as_view(), name='register'),

    path('profile/<int:pk>/', login_required(views.ProfileView.as_view()), name='profile'),

    path('logout/', LogoutView.as_view(http_method_names=["post", "get", "options"]), name='logout'),
]

backend/testquizapp/users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your username',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your password',
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your first name',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your last name',
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter username',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your email',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your password',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your password confirmation',
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class ProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'readonly': True
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'readonly': True
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

backend/testquizapp/users/views.py
from django.contrib import auth, messages
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView

from .forms import UserLoginForm, UserRegisterForm, ProfileForm
from django.contrib.auth.models import User

from main_app.models import UserTestResult, TestQuiz
from main_app.services import get_max_possible_score


# Create your views here.
class LoginUserView(LoginView):
    """Authenticate user view."""
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def form_invalid(self, form):
        messages.error(self.request, 'There was an error with username or password, check again !')
        return super().form_invalid(form)


class RegistrationView(CreateView):
    """Register user view."""
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('main_app:tests-page')

    def form_valid(self, form):
        response = super().form_valid(form)
        auth.login(self.request, self.object, backend='django.contrib.auth.backends.ModelBackend')
        return response

    def form_invalid(self, form):
        messages.error(self.request, 'There was an error with username or password, check again !')
        return super().form_invalid(form)


class ProfileView(UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'users/profile.html'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['test_history'] = UserTestResult.objects.filter(user=self.request.user)

        test_ids = TestQuiz.objects.all().values_list('id', flat=True)
        max_possible_score_dict = dict()

        for test_id in test_ids:
            max_possible_score_dict[test_id] = get_max_possible_score(test_id)

        context['max_possible_score_dict'] = max_possible_score_dict

        return context

backend/testquizapp/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% block styles %}{% endblock %}
</head>
<body>

{% block content %} {% endblock %}

<script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

backend/testquizapp/users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
   Login Page
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'users/css/login_register_style.css' %}">
{% endblock %}

{% block content %}
<body>
<div class="container">
    <div class="row justify-content-center login-container">
        <div class="col-md-6">
            <div class="logo">
                <h2>Please Log In</h2>
            </div>
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                    {{ message }}
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            {% endif %}
            <form action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">Username</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">Password</label>
                    {{ form.password }}
                </div>
                <button type="submit" class="btn btn-primary btn-block">Sign In</button>
            </form>
            <p class="signup-link">Not have an account? <a href="{% url 'users:register' %}">Sign Up</a></p>
        </div>
    </div>
</div>
{% endblock %}

backend/testquizapp/users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load static %}
{% load get_value_dict %}

{% block title %}
   User Profile
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'path/to/bootstrap/css/bootstrap.min.css' %}">
    <style>
        /* Add your custom styles here if needed */
        .test-card {
            margin-bottom: 20px;
        }
    </style>
{% endblock %}

{% block content %}

{% include 'main_app/header.html' %}

<div class="container mt-4">
 <div class="row">
        <div class="col-md-6">
            <h2>User Profile</h2>
            <p><strong>Name:</strong> {{ user.get_full_name }}</p>
            <p><strong>Nickname:</strong> {{ user.username }}</p>
            <p><strong>Tests Taken:</strong> {{ test_history|length }}</p>
            <a href="#" class="btn btn-primary">Ваші створені тести</a>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12">
            <h3>Test History</h3>
            {% for test in test_history|slice:5 %}
            <div class="card test-card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{% if test.test_quiz.image %}{{ test.test_quiz.image.url }}{% else %}{% static 'main_app/images/test-quiz.jpg' %}{% endif %}" class="card-img fixed-image" alt="Test Image">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ test.test_quiz.name }}</h5>
                            <p class="card-text"><strong>Date:</strong> {{ test.date_completed }}</p>
                            <p class="card-text"><strong>Correct Answers:</strong> {{ test.correct_questions }}</p>
                            <p class="card-text"><strong>Score:</strong> {{ test.score|default:0|add:0 }}/{{ max_possible_score_dict|hash:test.test_quiz.id }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

backend/testquizapp/users/templates/users/register.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
    Registration Page
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'users/css/login_register_style.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center login-container">
        <div class="col-md-6">
            <div class="logo">
                <h2>Please Sign Up</h2>
            </div>
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                    {{ message }}
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            {% endif %}
            <form action="{% url 'users:register' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">Username</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">Name</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}">Surname</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">Email Address</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password1.id_for_label }}">Password</label>
                    {{ form.password1 }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password2.id_for_label }}">Password Confirmation</label>
                    {{ form.password2 }}
                </div>
                <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
            </form>
            <p class="signup-link">Already have an account? <a href="{% url 'users:login' %}">Sign In</a></p>
        </div>
    </div>
</div>
{% endblock %}