backend/testquizapp/main_app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views
from . import api_views

app_name = 'main_app'

urlpatterns = [
    path('', login_required(views.TestsPageView.as_view()), name='tests-page'),
    path('create-test/', login_required(views.CreateTestView.as_view()), name='create-test'),
    path('create-question/', views.CreateQuestionsView.as_view(), name='create-question'),

    path('delete_test/<int:test_id>/', views.DeleteTestQuizView.as_view(), name='delete_test'),

    path('test-search/', views.TestSearchView.as_view(), name='test-search'),

    path('api-create-question/', api_views.GetQuestions.as_view(), name='api-create-question'),

    path('test-process/<int:test_id>/', views.TestProcessView.as_view(), name='test-process'),
    path('test-results/<int:test_id>/', views.TestResultsView.as_view(), name='test-results'),
    path('user-tests/', views.OwnTestsUserView.as_view(), name='user-tests'),
]

backend/testquizapp/testquizapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('main_app.urls', namespace='main_app')),
    path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='api-schema'), name='api-docs')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/testquizapp/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('signin/', views.LoginUserView.as_view(), name='login'),
    path('signup/', views.RegistrationView.as_view(), name='register'),

    path('profile/<int:pk>/', login_required(views.ProfileView.as_view()), name='profile'),

    path('logout/', LogoutView.as_view(http_method_names=["post", "get", "options"]), name='logout'),
]

backend/testquizapp/main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


class TestQuiz(models.Model):
    """Test quiz for storing what test it is."""

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='user_tests', null=True, blank=True)
    complexity = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(10)]
    )

    def __str__(self):
        return f'{self.name}, complexity: {self.complexity}'

class Question(models.Model):
    """Question's for the test."""

    test_quiz = models.ForeignKey(TestQuiz, on_delete=models.CASCADE, default=None)
    image = models.ImageField(upload_to='user_tests', null=True, blank=True)
    text = models.TextField()
    is_free_answer = models.BooleanField(default=False)
    is_only_one_correct_answer = models.BooleanField(default=False)
    is_few_correct_answers = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Choice(models.Model):
    """Choices for the question"""

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='user_tests', null=True, blank=True)
    text = models.CharField(max_length=255, null=True, blank=True)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.question}, is_correct: {self.is_correct}'


class UserTestResult(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test_quiz = models.ForeignKey(TestQuiz, on_delete=models.CASCADE)
    date_completed = models.DateTimeField(auto_now_add=True)
    correct_questions = models.IntegerField(default=0, blank=True, null=True)
    score = models.FloatField()
    is_passed = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} - {self.test_quiz.name} ({self.date_completed})'

class UserAnswer(models.Model):
    user_result = models.ForeignKey(UserTestResult, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    chosen_choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True, blank=True)
    text_answer = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.user_result.user.username} - {self.question.text}'

backend/testquizapp/main_app/forms.py
from django import forms
from .models import TestQuiz, Question, Choice


class TestQuizForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'required': 'true'
    }))
    description = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control', 'required': 'true'
    }))
    complexity = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'min': '1',
        'max': '10',
        'required': 'true'
    }))
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'class': 'form-control-file',
        'type': 'file',
        'accept': 'image/*',
        'onchange': 'displayFileName(this)'
    }), required=False)

    class Meta:
        model = TestQuiz
        fields = ['name', 'description', 'complexity', 'image']


class QuestionForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'true',
        'name': 'questions[]'
    }))
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'class': 'file-input-wrapper mt-2',
        'type': 'file',
        'id': 'questionImage',
        'accept': 'image/*',
        'onchange': 'displayFileName(this)',
        'name': 'questionImages[]'
    }), required=False)
    is_free_answer = forms.ChoiceField(widget=forms.Select(attrs={
        'class': 'form-control',
        'name': 'questionTypes[]',
    }), choices=[('free', 'Вільна відповідь'), ('single', 'Одна правильна відповідь'), ('multiple', 'Декілька правильних відповідей')])

    class Meta:
        model = Question
        fields = ['image', 'text', 'is_free_answer', 'is_only_one_correct_answer', 'is_few_correct_answers']

    def clean(self):
        cleaned_data = super().clean()
        is_free_answer = cleaned_data.get('is_free_answer')

        if is_free_answer == 'free':
            cleaned_data['is_free_answer'] = True
        elif is_free_answer == 'single':
            cleaned_data['is_only_one_correct_answer'] = True
        elif is_free_answer == 'multiple':
            cleaned_data['is_few_correct_answers'] = True

        return cleaned_data


class ChoiceForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'true',
        'name': 'choices[]'
    }), required=False)
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'class': 'file-input-wrapper mt-2',
        'type': 'file',
        'id': 'choiceImage',
        'accept': 'image/*',
        'onchange': 'displayFileName(this)',
        'name': 'choiceImages[]'
    }), required=False)
    is_correct = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'form-check-input',
        'name': 'is_correct[]'
    }), required=False)

    class Meta:
        model = Choice
        fields = ['image', 'text', 'is_correct']

    def clean(self):
        cleaned_data = super().clean()
        text = cleaned_data.get('text')
        image = cleaned_data.get('image')

        if not text and not image:
            raise forms.ValidationError('Either text or image is required.')

        return cleaned_data

backend/testquizapp/main_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, CreateView, TemplateView
from .forms import TestQuizForm
from .models import TestQuiz, Choice, Question
from django.db.models import Count
from django.views import View

from .services import CalculateResults, get_max_possible_score, get_ids_to_search


class TestsPageView(ListView):
    model = TestQuiz
    template_name = 'main_app/tests_page.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TestsPageView, self).get_context_data()

        context['tests_qty_questions'] = dict(
            Question.objects.values('test_quiz_id').annotate(
                questions_count=Count('id')
            ).values_list('test_quiz_id', 'questions_count')
        )

        return context


class CreateTestView(CreateView):
    model = TestQuiz
    form_class = TestQuizForm
    template_name = 'main_app/create_test.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        test_id = self.object.id
        return reverse('main_app:create-question') + f'?test_id={test_id}'


class CreateQuestionsView(TemplateView):
    template_name = 'main_app/create_questions.html'


class TestProcessView(ListView):
    model = Question
    template_name = 'main_app/test_process.html'

    def get_queryset(self):
        test_id = self.kwargs.get('test_id')
        queryset = super(TestProcessView, self).get_queryset()
        return queryset.filter(test_quiz_id=test_id)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TestProcessView, self).get_context_data(**kwargs)

        test_id = self.kwargs.get('test_id')
        questions_ids = Question.objects.filter(test_quiz_id=test_id).values_list('id', flat=True)
        choices_dict = {question_id: Choice.objects.filter(question_id=question_id) for question_id in questions_ids}

        context['choices_to_question'] = choices_dict
        context['test_id'] = test_id

        return context


class TestResultsView(View):
    template_name = 'main_app/test_results.html'

    def post(self, request, test_id, *args, **kwargs):
        context = dict(
            result=CalculateResults(test_id=test_id, request=request).get_results_of_test(),
            questions_count=Question.objects.filter(test_quiz_id=test_id).count(),
            max_possible_score=get_max_possible_score(test_id)
        )
        return render(request, template_name=self.template_name, context=context)

    def get(self, request, *args, **kwargs):
        return render(request, template_name=self.template_name)


class OwnTestsUserView(ListView):
    model = TestQuiz
    template_name = 'main_app/own_tests_user.html'

    def get_queryset(self):
        queryset = super(OwnTestsUserView, self).get_queryset()
        return queryset.filter(user=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OwnTestsUserView, self).get_context_data(**kwargs)

        test_ids = TestQuiz.objects.all().values_list('id', flat=True)
        max_possible_score_dict = dict()

        for test_id in test_ids:
            max_possible_score_dict[test_id] = get_max_possible_score(test_id)

        context['max_possible_score_dict'] = max_possible_score_dict

        return context


class DeleteTestQuizView(View):
    def get(self, request, test_id, *args, **kwargs):
        TestQuiz.objects.get(id=test_id).delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class TestSearchView(View):
    template_name = 'main_app/tests_page.html'

    def post(self, request, *args, **kwargs):
        search_query = str(dict(request.POST)['search_query'][0])
        test_ids = get_ids_to_search(search_query)

        context = dict(
            search_tests=TestQuiz.objects.filter(id__in=test_ids),
            search_query=str(search_query),
            search=True
        )

        context['tests_qty_questions'] = dict(
            Question.objects.values('test_quiz_id').annotate(
                questions_count=Count('id')
            ).values_list('test_quiz_id', 'questions_count')
        )

        return render(request, self.template_name, context)

backend/testquizapp/main_app/templates/main_app/create_questions.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
   Create Test Page
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'main_app/css/create_questions_styles.css' %}">
{% endblock %}

{% block content %}
{% include 'main_app/header.html' %}

<div class="create-test-container container mt-5">
    <h2>Create Test</h2>
    <form id="createTestForm" action="{% url 'main_app:tests-page' %}" onsubmit="collectFormData()" enctype="multipart/form-data">
        {% csrf_token %}

        <div id="questionsContainer"></div>

        <button type="button" class="btn btn-primary mt-2" onclick="addQuestion()">Add Question</button>
        <button type="submit" class="btn btn-success mt-2">Create Test</button>
    </form>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="{% static 'main_app/js/create_questions.js' %}"></script>

{% endblock %}

backend/testquizapp/main_app/templates/main_app/create_test.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
   Create Test Page
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'main_app/css/create_test_style.css' %}">
{% endblock %}

{% block content %}
{% include 'main_app/header.html' %}

<div class="page-container container mt-5">
    <div class="form-container">
        <h2>Create Test</h2>
        <form action="{% url 'main_app:create-test' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Test Name:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="{{ form.description.id_for_label }}">Test Description:</label>
                {{ form.description }}
            </div>
            <div class="form-group">
                <label for="{{ form.complexity.id_for_label }}">Difficulty (1-10):</label>
                {{ form.complexity }}
            </div>
            <div class="form-group">
                <label for="{{ form.image.id_for_label }}">Test Image:</label>
                <div class="file-input-wrapper">
                    <label for="testImage" class="btn btn-outline-primary">Upload Image</label>
                    {{ form.image }}
                    <span class="file-input-text"></span>
                </div>
            </div>
            <button type="submit">Next to create Questions</button>
        </form>
    </div>
</div>

<script>
    // Display selected file name
    function displayFileName(input) {
        var fileName = input.files[0].name;
        $(input).siblings('.file-input-text').text(fileName);
    }
</script>

{% endblock %}

backend/testquizapp/main_app/templates/main_app/header.html
<header class="bg-primary text-white py-3">
    <div class="container d-flex align-items-center justify-content-between">
        <a href="{% url 'main_app:tests-page' %}" class="text-white">
            <h1>Тести</h1>
        </a>

        <nav>
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-danger">Вийти</button>
                    </form>
                </li>
                <li class="list-inline-item">
                    <a href="{% url 'main_app:create-test' %}" class="btn btn-warning">Створити Тест</a>
                </li>
                <li class="list-inline-item">
                    <a href="{% url 'users:profile' user.id %}" class="btn btn-info">Профіль</a>
                </li>
            </ul>
        </nav>
    </div>
</header>

backend/testquizapp/main_app/templates/main_app/own_tests_user.html
{% extends 'users/base.html' %}
{% load static %}
{% load get_value_dict %}

{% block title %}
   Own Tests
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static '' %}">
    <style>
        .test-card {
            margin-bottom: 20px;
        }
    </style>
{% endblock %}

{% block content %}

{% include 'main_app/header.html' %}

<div class="container mt-4">
    <div class="row mt-4">
        <div class="col-md-12">
            <h3>Ваші тести</h3>
            {% for test in object_list %}
            <div class="card test-card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{% if test.image %}{{ test.image.url }}{% else %}{% static 'main_app/images/test-quiz.jpg' %}{% endif %}" class="card-img fixed-image" alt="Test Image">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ test.name }}</h5>
                            <p class="card-text"><strong>Date:</strong> {{ test.date_completed }}</p>
                            <p class="card-text"><strong>Correct Answers:</strong> {{ test.correct_questions }}</p>
                            <p class="card-text"><strong>Score:</strong> {{ test.score|default:0|add:0 }}/{{ max_possible_score_dict|hash:test.id }}</p>
                            <a href="{% url 'main_app:delete_test' test.id %}">
                                <button class="btn btn-danger delete-button float-right mb-2">Delete</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

backend/testquizapp/main_app/templates/main_app/test_process.html
{% extends 'users/base.html' %}
{% load static %}
{% load get_value_dict %}

{% block title %}
   Testing page
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static '' %}">
    <style>
    .fixed-image {
        width: 100px;
        height: 100px;
        object-fit: cover;
    }
</style>
{% endblock %}

{% block content %}
    {% include 'main_app/header.html' %}

    <section class="container mt-4">
    <form method="post" action="{% url 'main_app:test-results' test_id %}">
        {% csrf_token %}
        {% for question in object_list %}
            <div class="card mb-4">
                <div class="card-header">
                    {% if question.is_few_correct_answers %}
                        Питання (декілька правильних відповідей) <strong>+0.8-2 бали</strong>
                    {% elif question.is_only_one_correct_answer %}
                        Питання (тільки одна правильна відповідь) <strong>+1 бали</strong>
                    {% else %}
                        Питання (вільна відповідь) <strong>+2 бали</strong>
                    {% endif %}
                </div>
                <div class="card-body">
                    <p>{{ question.text }}</p>
                    {% if question.image %}
                        <img src="{{ question.image.url }}" class="img-fluid fixed-image rounded d-block" alt="Иллюстрация">{% endif %}

                    {% if question.is_free_answer %}
                        {% for answer in choices_to_question|hash:question.id %}
                            <div class="form-check">
                                <label for="freeResponse{{ answer.id }}">Ваша відповідь:</label>
                                <textarea class="form-control" id="freeResponse{{ answer.id }}" rows="2" name="user_answer_{{ question.id }} {{ answer.id }}"></textarea>
                            </div>
                        {% endfor %}
                    {% else %}
                        {% for answer in choices_to_question|hash:question.id %}
                            <div class="form-check">
                                <input type="{% if question.is_few_correct_answers %}checkbox{% else %}radio{% endif %}" class="form-check-input" id="answer{{ answer.id }}" name="user_answer_{{ question.id }}"
                                       value="{{ answer.id }}">
                                <label class="form-check-label" for="answer{{ answer.id }}"> {{ answer.text }} {% if answer.image %}
                                    <img src="{{ answer.image.url }}" class="img-thumbnail fixed-image rounded mx-auto d-block"
                                         alt="Иллюстрация 1">{% endif %}</label>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        {% endfor %}

        <div class="text-center mt-4">
            <button type="submit" class="btn btn-primary">Перевірити</button>
        </div>
    </form>
    </section>


{% endblock %}

backend/testquizapp/main_app/templates/main_app/test_results.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
   Testing page
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'main_app/css/test_results_styles.css' %}">
{% endblock %}

{% block content %}
    {% include 'main_app/header.html' %}

    <div class="container result-container text-center">
        <h2 class="result-heading mt-4">Результати теста</h2>
        <img src="{% static 'main_app/images/finish.png' %}" alt="Test Image" class="img-fluid test-image mt-4">
        <p class="user-info mt-4">Користувач: {{ result.user.username }}</p>
        <p class="user-info">Дата проходження: {{ result.date_completed }}</p>
        <p class="result-info">Правильних відповідей: {{ result.correct_questions }} из {{ questions_count }}</p>
        <p class="result-info">Загальний бал: {{ result.score|default:0|add:0 }}/{{ max_possible_score }}</p>

        <a href="{% url 'main_app:tests-page' %}" class="btn btn-primary btn-back mx-auto mt-4">Повернутися на головне меню</a>
    </div>
{% endblock %}

backend/testquizapp/main_app/templates/main_app/tests_page.html
{% extends 'users/base.html' %}
{% load static %}
{% load get_value_dict %}

{% block title %}
   Home Page
{% endblock %}

{% block content %}

{% include 'main_app/header.html' %}

<section class="py-3">
    <div class="container text-center">
        <form method="POST" action="{% url 'main_app:test-search' %}">
            {% csrf_token %}
            <div class="input-group mb-3">
                <input type="text" class="form-control" name="search_query" placeholder="Пошук тестів..." style="width: 70%;">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-primary">Знайти</button>
                </div>
            </div>
        </form>
    </div>
</section>

<section class="py-5">
    <div class="container">
        <h2 class="text-center mb-4">{% if not search %}Тести{% else %}Тести за пошуком: {{ search_query }}{% endif %}</h2>
        <div class="row">
        {% if not search %}
            {% for test in object_list %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <img src="{% if test.image %}{{ test.image.url }}{% else %}{% static 'main_app/images/test-quiz.jpg' %}{% endif %}" class="card-img-top" alt="Test Image">
                        <div class="card-body">
                            <h5 class="card-title">{{ test.name }}</h5>
                            <p class="card-text">Опис: {{ test.description|truncatewords:30 }}</p>
                            <p class="card-text">Кількість питань: {{ tests_qty_questions|hash:test.id }}</p>
                            <p class="card-text">Складність: {{ test.complexity }}</p>
                            <a href="{% url 'main_app:test-process' test.id %}" class="btn btn-primary">Пройти тест</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% else %}
        {% for test in search_tests %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <img src="{% if test.image %}{{ test.image.url }}{% else %}{% static 'main_app/images/test-quiz.jpg' %}{% endif %}" class="card-img-top" alt="Test Image">
                        <div class="card-body">
                            <h5 class="card-title">{{ test.name }}</h5>
                            <p class="card-text">Опис: {{ test.description|truncatewords:30 }}</p>
                            <p class="card-text">Кількість питань: {{ tests_qty_questions|hash:test.id }}</p>
                            <p class="card-text">Складність: {{ test.complexity }}</p>
                            <a href="{% url 'main_app:test-process' test.id %}" class="btn btn-primary">Пройти тест</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</section>

{% endblock %}